export const API = {
  openMarket: "",
  changePassword: "",
  login: "",
  auth: "",
  openOrders: "",
  runners: "",
  tv: "",
  result: "",
  index: "",
  viewClient: "",
  statement: "",
  up: "",
};

export const Settings = {
  bonus: "",
  deposit: "",
  withdraw: "",
  register: "",
  demoLogin: "",
  disabledDevtool: "",
  otp: "",
  casinoCurrency: "",
  siteUrl: "",
  siteTitle: "",
  interval: "",
  forceLogin: "",
  casinoType: "",
};
